import "./globals.css"
import "normalize.css/normalize.css"
import { Roboto } from "next/font/google"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const font = Roboto({
  weight: ["500", "700", "900"],
  subsets: ["latin"],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={font.className}>
      <body>{children}</body>
    </html>
  )
}
