import "./globals.css"
import "normalize.css/normalize.css"
import { Roboto } from "next/font/google"

export const metadata = {
  title: "ZDOROVO | Estudia en Rusia",
  description: "Generated by create next app",
}

const font = Roboto({
  weight: ["500", "700", "900"],
  subsets: ["latin"],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`overflow-x-hidden ${font.className}`}>
      <body>{children}</body>
    </html>
  )
}
